### ISSUE TITLE
[Request] Disable ability when the building haven't finished

### ISSUE THREAD

**Issue by Septica** [MNoya/BuildingHelper#9]
The title says it all. Apparently you can use building abilities while the building is being built

**Comment by MNoya** [comment]
You can do this yourself via builder.lua callbacks, just silence/stun the building in `event:OnConstructionStarted` and remove it in `event:OnConstructionCompleted`. The reason this isn't the default behaviour is because this way it is possible to queue abilities as soon as the building starts, to resume them later when it finishes construction.
